name = "rbs"
main = "functions/_middleware.js"
compatibility_date = "2023-05-18"

[env.production]
name = "rbs"

[env.preview]
name = "rbs-preview"

[[kv_namespaces]]
binding = "RBS_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[vars]
ADMIN_PASSWORD = "rbs2025admin"

[env.production.vars]
ADMIN_PASSWORD = "your-production-password"

[env.preview.vars]
ADMIN_PASSWORD = "preview-password" 